// Original branded artwork (generated by scripts/gen-art.mjs into public/art/).
// The site does not reuse photography from aromasenseusa.com.

export const lifestyle = {
  bathroom: '/art/hero.svg',
  shower: '/art/page-1.svg',
  showerAlt: '/art/page-2.svg',
  robe: '/art/feature-tall.svg',
  robeMan: '/art/page-3.svg',
  hair: '/art/feature-tall.svg',
  morning: '/art/feature-wide.svg',
  vitaminC: '/art/feature-wide.svg',
} as const

// A three-step ritual — art + copy for the editorial band.
export const ritual = [
  {
    step: 'I',
    title: 'Filter',
    body: 'Microfiber media traps rust and sediment; pharmaceutical-grade vitamin C neutralizes chlorine on contact.',
    image: '/art/ritual-1.svg',
  },
  {
    step: 'II',
    title: 'Infuse',
    body: 'Warm water carries natural essential oils into the air — lavender, citrus, eucalyptus, forest.',
    image: '/art/ritual-2.svg',
  },
  {
    step: 'III',
    title: 'Restore',
    body: 'Softer water and stronger, fuller pressure leave hair and skin conditioned, calm and cared for.',
    image: '/art/ritual-3.svg',
  },
]

export const gallery = [
  { src: '/art/look-1.svg', caption: 'The hotel-spa shower, at home' },
  { src: '/art/look-2.svg', caption: 'A healthier hair routine' },
  { src: '/art/look-3.svg', caption: 'The end-of-day ritual' },
  { src: '/art/look-4.svg', caption: 'Vitamin C, every morning' },
]
